### ISSUE TITLE
Missing configuration files in run_dist.py

### ISSUE THREAD

**Issue by chjchjchjchjchj** [nasheydari/HypOp#2]
I am looking at the code in `run_dist.py` and noticed several configuration files seem missing. Specifically, the following files are referenced but do not appear to be present in the repository:

1. `infer_configs/maxcut_R_for.json` (referenced at [run_dist.py#L13](https://github.com/nasheydari/HypOp/blob/main/run_dist.py#L13))
2. `infer_configs/maxcut_arxiv_for.json` (referenced at [run_dist.py#L16](https://github.com/nasheydari/HypOp/blob/main/run_dist.py#L16))
3. `dist_configs/maxcut_R_for.json` (referenced at [run_dist.py#L22](https://github.com/nasheydari/HypOp/blob/main/run_dist.py#L22))
4. `dist_configs/maxcut_arxiv_for.json` (referenced at [run_dist.py#L25](https://github.com/nasheydari/HypOp/blob/main/run_dist.py#L25))

Could you please provide these files or update the repository with the necessary configurations? Thank you!

**Comment by nasheydari** [comment]
I uploaded the config files. I also updated the rest of the repo to be compatible with these config files. Please pull the new updates and let me know if you have any issues running the code.

**Comment by chjchjchjchjchj** [comment]
Thank you for providing the configuration files for maxcut.

I am now looking for configuration files for maximum independent set (maxind) Distributed GPU Training. Are there any existing configuration files for this purpose? If so, could you please point me to them or provide them?

Thank you for your assistance!
