### ISSUE TITLE
Can you share the configuration file about SAT experiments and datasets in supplementary information?

### ISSUE THREAD

**Issue by happypu326** [nasheydari/HypOp#6]
Thanks to the shared code. In the appendix of the article, regarding the SAT experiment, it is mentioned that 100 satisfiable instances each of four different sizes were selected from SATLIB. Could you please provide these selected instances? Additionally, in the publicly available code, there seems to be a lack of configuration details for the SAT solver. Could you also share the configuration file for this part?

**Comment by nasheydari** [comment]
Hi. We used uf examples from SATLIB, which can be found here: https://www.cs.ubc.ca/~hoos/SATLIB/benchm.html
I uploaded a config file for SAT problems.
